### PR TITLE
Fix/add non zero exit for coverage fail

### PR DESCRIPTION
**Pull request by michael-okeefe**
This causes the `rake` (or `rake coverage`) command to return a non-zero exit code if there are any coverage failures.

Let me know if you would like any changes.

Reference: #200 

NOTE: since there are coverage check issues and the purpose of this task is to return a non-zero exit code when there are coverage issues, we should see a failure on the CI (related to docs build).

### CODE REVIEW

**Comment by nealkruis** [comment]
@galanCA can you merge this into your documentation branch to test it?

**Comment by galanCA** [comment]
Yes.

**Comment by galanCA** [comment]
I was able to test the changes and eliminating all records and data inconsistencies will work. This should probably be merge with address-doc-coverage, once we decide the path that we should take for deprecated records that are still in CSE.

**Comment by nealkruis** [comment]
There should really be an error message printed so a user has some context as to why the documentation build "failed". Otherwise, it appears everything was successful, but returned a non-zero exit code:

Screen Shot 2022-03-31 at 11 51 50 AM

**Comment by nealkruis** [comment]
@michael-okeefe can you also add a method to ignore certain coverage failures? That's what we should probably do for the unsupported records for now.

**Comment by michael-okeefe** [comment]
> @michael-okeefe can you also add a method to ignore certain coverage failures? That's what we should probably do for the unsupported records for now.

Sure thing. I'll do the following:

* split out "building the docs" from running the coverage report; that way, if the actual docs building fails, you'll know
* update the feedback message for the coverage report to be more useful

@nealkruis , could you clarify what you mean by "ignoring coverage failures"? I'm not sure what is meant by "unsupported records"; I've attached the coverage report run off of the master branch -- is there a category of things we should be ignoring?

[documentation-coverage-report.txt](https://github.com/cse-sim/cse/files/8392423/documentation-coverage-report.txt)

**Comment by nealkruis** [comment]
@michael-okeefe, I'm thinking of somewhere in [cse-user-manual.yaml](https://github.com/cse-sim/cse/blob/master/doc/src/cse-user-manual.yaml) where we can indicate certain records, or data fields for the coverage to ignore when considering if it should fail or not. Something like:

```
ignore-coverage:
  records:
   - "airHandler"
  data-fields:
    export:
      - "exTu"
```

**Comment by michael-okeefe** [comment]
@nealkruis Just updated with the `ignore-coverage` functionality and the other changes mentioned above. This one should still fail but just for the `Run coverage check` step of `build-doc`.

**Comment by galanCA** [comment]
@nealkruis  This work great. Thank you @michael-okeefe.

**Comment by nealkruis** [comment]
I'm going to let this merge in with #181. I'll close it once that PR is merged.

**Comment by galanCA** [comment]
@michael-okeefe I am having issues ignoring data fields. It is ignoring records fine. I am not sure if I am [implementing it wrong](https://github.com/cse-sim/cse/blob/address-doc-coverage/doc/src/cse-user-manual.yaml#L31-L48). Below is the terminal output. 

image

**Comment by michael-okeefe** [comment]
> @michael-okeefe I am having issues ignoring data fields. It is ignoring records fine. I am not sure if I am [implementing it wrong](https://github.com/cse-sim/cse/blob/address-doc-coverage/doc/src/cse-user-manual.yaml#L31-L48). Below is the [terminal output](https://github.com/cse-sim/cse/runs/5793856498?check_suite_focus=true). Do you know what the issue is?
> 
> image

Hi @galanCA , I'll take a look as soon as I can. It looks like you have it set up correctly so it is probably a bug.

**Comment by galanCA** [comment]
Thank you!

**Comment by michael-okeefe** [comment]
Hi @galanCA , I just tried on the `address-doc-coverage` branch on my local machine and get:

```
Check CSE User Manual's Documentation Coverage
........................
Ignoring the following records (and any subsequent field discrepancies):
- inverse

Ignoring the following fields:
- coolplant:cpStage2
- coolplant:cpStage3
- coolplant:cpStage4
- coolplant:cpStage5
- coolplant:cpStage6
- coolplant:cpStage7
- heatplant:hpStage2
- heatplant:hpStage3
- heatplant:hpStage4
- heatplant:hpStage5
- heatplant:hpStage6
- heatplant:hpStage7


DATA FIELD INCONSISTENCIES:
top:
    in CSE but not in Documentation:
    - clear
    - run

Coverage Check: FAILED
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

I'm not seeing the coolplant or heatplant field issues. Was the screenshot you provided from your local machine? On on the CI? Both?

What version of Ruby are you running? (I'm using Ruby 2.7, 64-bit on a shell with Pandoc 1.17.2 and the Visual Studio compiler environment active).

**Comment by galanCA** [comment]
The screenshot was from the CI, but I was also seeing it locally. I just added them back temporarily but you can [checkout this commit](https://github.com/cse-sim/cse/pull/181/commits/2b30eb7d5e9451152dda0e8ec4ab67a7a50beb6c) to test it. 

Those inconsistencies were removed from `CSE -c` in `address-doc-coverage`.

PS: I delete them again so you can work from that commit or from the head of the branch.

**Comment by michael-okeefe** [comment]
@galanCA I'll try that commit to see if I can reproduced it. Thanks!

**Comment by michael-okeefe** [comment]
@galanCA , thank you for creating that commit for me -- that made it easy to see and address the issue.

I believe this is fixed now and I just pushed it to `fix/add-non-zero-exit-for-coverage-fail` and also `address-doc-coverage`. The issue was a bug in how I was handling the case-insensitive compare when coolPlant and heatPlant appear cased in the cull list. Let me know if you run into anything else.

**Comment by michael-okeefe** [comment]
Hello All, hold off on merging this for a second as I'm going to add unit tests and update the README so we have that down for the future. Should be within the next hour.

**Comment by michael-okeefe** [comment]
@nealkruis , @galanCA , I just updated the `README.md` in docs/ and also added some unit testing for the changes related to ignoring records. All of those changes have been pushed up on the current branch (`fix/add-non-zero-exit-for-coverage-fail`) and `address-docs-coverage`.

I *think* this should be good to go now but let me know if there is anything else.

**Comment by galanCA** [comment]
Thank you, Michael. This will be merged at the same time as `doc-address-coverages`.

**Pull request merged**
