### PR TITLE
Fix versioning

### PR DESCRIPTION
**Pull request by tanaya-bigladder**
Address Issue #101 .
Any failure to capture branch/tag/build information from git will now result in a failure when CSEVersion.cmake is executed (early in the build process). If the version doesn't conform to "`v<major>.<minor>.<patch>-<optional_prerelease_label>`" it will also fail in the CMake script.
The final version, with metadata, conforms to semver.org guidelines.

### CODE REVIEW

**Comment by nealkruis** [comment]
@tanaya-bigladder what do you think about adding some build meta data to indicate a "dirty" build (i.e., with uncommitted changes)?

**Comment by nealkruis** [comment]
@tanaya-bigladder what do you think about adding some build meta data to indicate a "dirty" build (i.e., with uncommitted changes)?

**Comment by tanaya-bigladder** [comment]
Most builds are dirty, aren't they? Just the existence of a branch name other than "master" would indicate that generally. I don't think it's a lot of work, but is there value in it if we are generally careful about releases?

**Comment by nealkruis** [comment]
@tanaya-bigladder, I would not say most builds are dirty. A branch off of master does not make the build dirty. It is only dirty if there are uncommitted changes in the working copy.

**Comment by tanaya-bigladder** [comment]
I've never had the experience of needing this information, but I can add it here especially if @nealkruis thinks it'll be useful for atheneum-based libraries in the future.

**Comment by tanaya-bigladder** [comment]
OK, a solution is checked in! It's not my most ideal (`git status --porcelain` has a guaranteed interface over time whereas `git diff --shortstat` might not) but it will work without adding another script to parse the output of status.

**Review by nealkruis — APPROVED** [review]

**Pull request merged**
