### PR TITLE
Remove extra qualification in calendar constructor.

### PR DESCRIPTION
**Pull request by galanCA**
## Description

Removes extra qualification on calendar constructor in TDPAK.H.

## Author Progress Checklist:

- [ ] Open draft pull request
    - [x] Make title clearly understandable in a standalone change log context
    - [x] Assign yourself the issue
    - [x] Add at least one label (enhancement, bug, or maintenance)
    - [ ] Link the issue(s) addressed by this PR (under "Development" in the sidebar menu) 
- [ ] Make code changes (if you haven't already)
- [ ] Self-review of code
    - [ ] My code follows the style guidelines of this project
    - [ ] I have added comments to my code, particularly in hard-to-understand areas
    - [ ] I have only committed the necessary changes for this fix or feature
    - [ ] I have made corresponding changes to the documentation
    - [ ] My changes generate no new warnings
    - [ ] I have ensured that my fix is effective or that my feature works as intended by:
        - [ ] exercising the code changes in the test framework, and/or
        - [ ] manually verifying the changes (as explained in the the pull request description above)
    - [ ] My changes pass all local tests
    - [ ] My changes successfully passes CI checks
    - [ ] Add any unit test for proof and documentation.
    - [ ] Merge in main branch and address resulting conflicts and/or test failures.
- [ ] Move pull request out of draft mode and assign reviewers
- [ ] Iterate with reviewers until all changes are approved
    - [ ] Make changes in response to reviewer comments
    - [ ] Merge in main branch and address resulting conflicts and/or test failures.
    - [ ] Re-request review in GitHub

## Reviewer Checklist:

 - [ ] Read the pull request description
 - [ ] Perform a code review on GitHub
 - [ ] Confirm all CI checks pass and there are no build warnings
 - [ ] Pull, build, and run automated tests locally
 - [ ] Perform manual tests of the fix or feature locally
 - [ ] Add any review comments, if applicable
 - [ ] Submit review in GitHub as either
     - [ ] Request changes, or
     - [ ] Approve
 - [ ] Iterate with author until all changes are approved

### CODE REVIEW

**Review by tanaya-bigladder — COMMENTED** [review]
I'm not sure we are doing cleanup at this trivial level. Was this relevant to either multi-platform or any of your other tasks?

**Comment by galanCA** [comment]
This is related to multi-platform. Both GCC and Clang complain about this error.

**Review by tanaya-bigladder — APPROVED** [review]
In the future, please leave a comment about what this change fixes. 
We've got a checkbox for the reviewer to read the PR description, so it should be descriptive!

**Comment by galanCA** [comment]
Yes. I thought that by adding the label, it should imply that it is for the multi-platform. I will add it to the description as well.

**Pull request merged**
